DROP TABLE IF EXISTS TBL_CALL_DISTRIBUTIONS;

CREATE TABLE TBL_CALL_DISTRIBUTIONS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	date_time TIMESTAMP,
	reason	VARCHAR(250) NOT NULL,
	location_name VARCHAR(250) NOT NULL,
	telephone_number VARCHAR(250) NOT NULL
);